### ISSUE TITLE
Campaign & Donation reports to be online + Period wise

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#239] opened 2015-07-01 12:24 UTC
The donations and campaign report from the admin dashboard to be online (connected to a google doc maybe). Also to have it period-wise.

To be sorted Newest-Oldest

**Comment by kuchlous** [comment] 2015-12-12 06:28
Duplicate of #305. Closing.

**Closed by kuchlous** 2015-12-12 06:28 UTC
