### ISSUE TITLE
FB + website links of beneficiaries missing

### ISSUE THREAD

**Issue by purvishah77** [PrathamBooks/frp#203] opened 2015-06-23 16:35 UTC
On Campaign page there is no url for beneficiary or FB page link etc. 

Use case: Donor wants to read more about the beneficiary before donating. See more pictures etc.

**Comment by kuchlous** [comment] 2015-06-23 16:45
duplicate of Issue #158 .

**Closed by kuchlous** 2015-06-23 16:45 UTC
Labels: enhancement
