### ISSUE TITLE
For Fully Funded, can button change to Funded in place of donate

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#222] opened 2015-06-26 04:42 UTC
This campaign is fully funded. But donate button still active. Even though clicking it pops up a message saying it’s fully funded. Can’t we change the button to “Funded!” or something once it is 100% funded?

![image](https://cloud.githubusercontent.com/assets/12147445/8370841/d58e8776-1beb-11e5-8061-ba5b29452d45.png)

**Comment by kuchlous** [comment] 2015-06-26 04:47
Duplicate of #37 please add feedback there.

**Closed by kuchlous** 2015-06-26 04:47 UTC
