### ISSUE TITLE
Error shown while logging in via Facebook

### ISSUE THREAD

**Issue by Payoshni** [PrathamBooks/frp#285] opened 2015-09-14 05:16 UTC
Gautam's friend encountered this error while trying to login via FB:

![gkj screenshot](https://cloud.githubusercontent.com/assets/12147445/9842590/b3085d8c-5acd-11e5-934d-6349852c5e65.png)
 logged this.

**Comment by kuchlous** [comment] 2015-09-14 05:35
@RCReddy check the logs.

@Payoshni can you find the approximate time when this happened.

**Comment by Payoshni** [comment] 2015-09-14 05:48
checked. GKJ says approximately between 7 a.m to 8 a.m

Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by kuchlous** [comment] 2015-09-14 06:15
Can you ask him to try again. We received a bad response from FB for his request.

**Comment by Payoshni** [comment] 2015-09-14 07:00
Alok,
elaborate more please? What is 'bad response'? How do I explain this to him?


Regards,
Payoshni

“Someone reading a Book is a sign of order in the world”

-Mary Ruefle

**Comment by kuchlous** [comment] 2015-09-14 07:40
I am not sure either. You just have to say there was some error from
Facebook so please try again.

**Comment by kuchlous** [comment] 2015-10-09 04:52
Cannot reproduce. Closing.

**Closed by kuchlous** 2015-10-09 04:52 UTC
Labels: bug
